/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\VSCode\\VuePress-Blog\\personnal-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4e2589a8",
    path: "/handbook/Byte/notes-react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e2589a8").then(next)
    },
  },
  {
    name: "v-33cba05a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33cba05a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-fa9d4098",
    path: "/handbook/ES6/Promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa9d4098").then(next)
    },
  },
  {
    name: "v-3caecaa8",
    path: "/handbook/Byte/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3caecaa8").then(next)
    },
  },
  {
    name: "v-04c3f5f4",
    path: "/handbook/ES6/for-in-of.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04c3f5f4").then(next)
    },
  },
  {
    name: "v-29052a20",
    path: "/handbook/ES6/async-await.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29052a20").then(next)
    },
  },
  {
    name: "v-34526722",
    path: "/handbook/ES6/hand-promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34526722").then(next)
    },
  },
  {
    name: "v-2f587472",
    path: "/handbook/Git/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f587472").then(next)
    },
  },
  {
    name: "v-7396af44",
    path: "/handbook/ES6/generator.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7396af44").then(next)
    },
  },
  {
    name: "v-740c6c70",
    path: "/handbook/Javascript/NaN.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-740c6c70").then(next)
    },
  },
  {
    name: "v-89b357f0",
    path: "/handbook/Javascript/Array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-89b357f0").then(next)
    },
  },
  {
    name: "v-1e72e1f0",
    path: "/handbook/Javascript/clourse.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e72e1f0").then(next)
    },
  },
  {
    name: "v-415673b4",
    path: "/handbook/Javascript/copy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-415673b4").then(next)
    },
  },
  {
    name: "v-3cfeb528",
    path: "/handbook/Javascript/design-mode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3cfeb528").then(next)
    },
  },
  {
    name: "v-46361b30",
    path: "/handbook/Javascript/eventloop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46361b30").then(next)
    },
  },
  {
    name: "v-448482b0",
    path: "/handbook/Javascript/cross.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-448482b0").then(next)
    },
  },
  {
    name: "v-5a59ae30",
    path: "/handbook/Javascript/new.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a59ae30").then(next)
    },
  },
  {
    name: "v-c94833b0",
    path: "/handbook/Javascript/scope.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c94833b0").then(next)
    },
  },
  {
    name: "v-18ae93ea",
    path: "/handbook/Javascript/type.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18ae93ea").then(next)
    },
  },
  {
    name: "v-b020dfbc",
    path: "/handbook/Javascript/this.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b020dfbc").then(next)
    },
  },
  {
    name: "v-64b915e8",
    path: "/handbook/Javascript/prototype.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64b915e8").then(next)
    },
  },
  {
    name: "v-2534b6da",
    path: "/handbook/Javascript/web-router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2534b6da").then(next)
    },
  },
  {
    name: "v-66562fc2",
    path: "/handbook/Javascript/url-render-bot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66562fc2").then(next)
    },
  },
  {
    name: "v-a7e376b4",
    path: "/handbook/Javascript/url-render-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7e376b4").then(next)
    },
  },
  {
    name: "v-1230f3c8",
    path: "/handbook/NodeJS/onion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1230f3c8").then(next)
    },
  },
  {
    name: "v-81c9c4ec",
    path: "/handbook/NodeJS/http.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81c9c4ec").then(next)
    },
  },
  {
    name: "v-71ef9468",
    path: "/handbook/Typescript/ts-type.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71ef9468").then(next)
    },
  },
  {
    name: "v-4d47a048",
    path: "/handbook/Typescript/judge.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d47a048").then(next)
    },
  },
  {
    name: "v-bf6ce736",
    path: "/handbook/Vue%20Series/communicate.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bf6ce736").then(next)
    },
  },
  {
    path: "/handbook/Vue Series/communicate.html",
    redirect: "/handbook/Vue%20Series/communicate.html"
  },
  {
    path: "/handbook/Vue Series/communicate.html",
    redirect: "/handbook/Vue%20Series/communicate.html"
  },
  {
    name: "v-c30d43b6",
    path: "/handbook/Vue%20Series/define-router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c30d43b6").then(next)
    },
  },
  {
    path: "/handbook/Vue Series/define-router.html",
    redirect: "/handbook/Vue%20Series/define-router.html"
  },
  {
    path: "/handbook/Vue Series/define-router.html",
    redirect: "/handbook/Vue%20Series/define-router.html"
  },
  {
    name: "v-565a596b",
    path: "/handbook/Vue%20Series/diff-vue23.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-565a596b").then(next)
    },
  },
  {
    path: "/handbook/Vue Series/diff-vue23.html",
    redirect: "/handbook/Vue%20Series/diff-vue23.html"
  },
  {
    path: "/handbook/Vue Series/diff-vue23.html",
    redirect: "/handbook/Vue%20Series/diff-vue23.html"
  },
  {
    name: "v-948b1d76",
    path: "/handbook/Vue%20Series/key-index.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-948b1d76").then(next)
    },
  },
  {
    path: "/handbook/Vue Series/key-index.html",
    redirect: "/handbook/Vue%20Series/key-index.html"
  },
  {
    path: "/handbook/Vue Series/key-index.html",
    redirect: "/handbook/Vue%20Series/key-index.html"
  },
  {
    name: "v-54dc40c0",
    path: "/handbook/%E6%B5%8F%E8%A7%88%E5%99%A8/XSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54dc40c0").then(next)
    },
  },
  {
    path: "/handbook/浏览器/XSS.html",
    redirect: "/handbook/%E6%B5%8F%E8%A7%88%E5%99%A8/XSS.html"
  },
  {
    path: "/handbook/浏览器/XSS.html",
    redirect: "/handbook/%E6%B5%8F%E8%A7%88%E5%99%A8/XSS.html"
  },
  {
    name: "v-4045a79d",
    path: "/handbook/Vue%20Series/params.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4045a79d").then(next)
    },
  },
  {
    path: "/handbook/Vue Series/params.html",
    redirect: "/handbook/Vue%20Series/params.html"
  },
  {
    path: "/handbook/Vue Series/params.html",
    redirect: "/handbook/Vue%20Series/params.html"
  },
  {
    name: "v-ffa9b532",
    path: "/handbook/%E6%89%8B%E5%86%99%E9%A2%98/flat.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ffa9b532").then(next)
    },
  },
  {
    path: "/handbook/手写题/flat.html",
    redirect: "/handbook/%E6%89%8B%E5%86%99%E9%A2%98/flat.html"
  },
  {
    path: "/handbook/手写题/flat.html",
    redirect: "/handbook/%E6%89%8B%E5%86%99%E9%A2%98/flat.html"
  },
  {
    name: "v-fd6d00aa",
    path: "/handbook/%E6%89%8B%E5%86%99%E9%A2%98/call-apply-bind.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fd6d00aa").then(next)
    },
  },
  {
    path: "/handbook/手写题/call-apply-bind.html",
    redirect: "/handbook/%E6%89%8B%E5%86%99%E9%A2%98/call-apply-bind.html"
  },
  {
    path: "/handbook/手写题/call-apply-bind.html",
    redirect: "/handbook/%E6%89%8B%E5%86%99%E9%A2%98/call-apply-bind.html"
  },
  {
    name: "v-cf20034c",
    path: "/handbook/%E9%9D%A2%E8%AF%95%E9%A2%98/bigfileload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf20034c").then(next)
    },
  },
  {
    path: "/handbook/面试题/bigfileload.html",
    redirect: "/handbook/%E9%9D%A2%E8%AF%95%E9%A2%98/bigfileload.html"
  },
  {
    path: "/handbook/面试题/bigfileload.html",
    redirect: "/handbook/%E9%9D%A2%E8%AF%95%E9%A2%98/bigfileload.html"
  },
  {
    name: "v-0c9df344",
    path: "/views/About/author.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c9df344").then(next)
    },
  },
  {
    name: "v-a6051270",
    path: "/views/Resume/resume.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6051270").then(next)
    },
  },
  {
    name: "v-11de394e",
    path: "/views/other/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11de394e").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-27c59f82",
    path: "/tag/青训营笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-27c59f82").then(next)
    },
    meta: {"pid":"tags","id":"青训营笔记"}
  },
  {
    path: "/tag/青训营笔记/index.html",
    redirect: "/tag/青训营笔记/"
  },
  {
    name: "v-d0674184",
    path: "/tag/Promise/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d0674184").then(next)
    },
    meta: {"pid":"tags","id":"Promise"}
  },
  {
    path: "/tag/Promise/index.html",
    redirect: "/tag/Promise/"
  },
  {
    name: "v-1f35fe62",
    path: "/tag/for-of-in/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1f35fe62").then(next)
    },
    meta: {"pid":"tags","id":"for-of-in"}
  },
  {
    path: "/tag/for-of-in/index.html",
    redirect: "/tag/for-of-in/"
  },
  {
    name: "v-5dd7c1b4",
    path: "/tag/async-await/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5dd7c1b4").then(next)
    },
    meta: {"pid":"tags","id":"async-await"}
  },
  {
    path: "/tag/async-await/index.html",
    redirect: "/tag/async-await/"
  },
  {
    name: "v-32555732",
    path: "/tag/Git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32555732").then(next)
    },
    meta: {"pid":"tags","id":"Git"}
  },
  {
    path: "/tag/Git/index.html",
    redirect: "/tag/Git/"
  },
  {
    name: "v-9114abf4",
    path: "/tag/Generator/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-9114abf4").then(next)
    },
    meta: {"pid":"tags","id":"Generator"}
  },
  {
    path: "/tag/Generator/index.html",
    redirect: "/tag/Generator/"
  },
  {
    name: "v-07a3e910",
    path: "/tag/javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-07a3e910").then(next)
    },
    meta: {"pid":"tags","id":"javascript"}
  },
  {
    path: "/tag/javascript/index.html",
    redirect: "/tag/javascript/"
  },
  {
    name: "v-197ac33a",
    path: "/tag/数组/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-197ac33a").then(next)
    },
    meta: {"pid":"tags","id":"数组"}
  },
  {
    path: "/tag/数组/index.html",
    redirect: "/tag/数组/"
  },
  {
    name: "v-eec8ec48",
    path: "/tag/闭包/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-eec8ec48").then(next)
    },
    meta: {"pid":"tags","id":"闭包"}
  },
  {
    path: "/tag/闭包/index.html",
    redirect: "/tag/闭包/"
  },
  {
    name: "v-d74bd976",
    path: "/tag/深浅拷贝/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d74bd976").then(next)
    },
    meta: {"pid":"tags","id":"深浅拷贝"}
  },
  {
    path: "/tag/深浅拷贝/index.html",
    redirect: "/tag/深浅拷贝/"
  },
  {
    name: "v-ae3001b6",
    path: "/tag/设计模式/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-ae3001b6").then(next)
    },
    meta: {"pid":"tags","id":"设计模式"}
  },
  {
    path: "/tag/设计模式/index.html",
    redirect: "/tag/设计模式/"
  },
  {
    name: "v-1960ed2f",
    path: "/tag/浏览器的事件循环/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1960ed2f").then(next)
    },
    meta: {"pid":"tags","id":"浏览器的事件循环"}
  },
  {
    path: "/tag/浏览器的事件循环/index.html",
    redirect: "/tag/浏览器的事件循环/"
  },
  {
    name: "v-67cf2c0a",
    path: "/tag/跨域/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-67cf2c0a").then(next)
    },
    meta: {"pid":"tags","id":"跨域"}
  },
  {
    path: "/tag/跨域/index.html",
    redirect: "/tag/跨域/"
  },
  {
    name: "v-970225a0",
    path: "/tag/new原理/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-970225a0").then(next)
    },
    meta: {"pid":"tags","id":"new原理"}
  },
  {
    path: "/tag/new原理/index.html",
    redirect: "/tag/new原理/"
  },
  {
    name: "v-033f6638",
    path: "/tag/作用域和作用域链/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-033f6638").then(next)
    },
    meta: {"pid":"tags","id":"作用域和作用域链"}
  },
  {
    path: "/tag/作用域和作用域链/index.html",
    redirect: "/tag/作用域和作用域链/"
  },
  {
    name: "v-0b8093b7",
    path: "/tag/类型转换/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0b8093b7").then(next)
    },
    meta: {"pid":"tags","id":"类型转换"}
  },
  {
    path: "/tag/类型转换/index.html",
    redirect: "/tag/类型转换/"
  },
  {
    name: "v-28ccba78",
    path: "/tag/关键字this/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-28ccba78").then(next)
    },
    meta: {"pid":"tags","id":"关键字this"}
  },
  {
    path: "/tag/关键字this/index.html",
    redirect: "/tag/关键字this/"
  },
  {
    name: "v-53c426ac",
    path: "/tag/原型和原型链/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-53c426ac").then(next)
    },
    meta: {"pid":"tags","id":"原型和原型链"}
  },
  {
    path: "/tag/原型和原型链/index.html",
    redirect: "/tag/原型和原型链/"
  },
  {
    name: "v-b612eeb2",
    path: "/tag/前端路由/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-b612eeb2").then(next)
    },
    meta: {"pid":"tags","id":"前端路由"}
  },
  {
    path: "/tag/前端路由/index.html",
    redirect: "/tag/前端路由/"
  },
  {
    name: "v-322b436c",
    path: "/tag/url/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322b436c").then(next)
    },
    meta: {"pid":"tags","id":"url"}
  },
  {
    path: "/tag/url/index.html",
    redirect: "/tag/url/"
  },
  {
    name: "v-0c5c4c5e",
    path: "/tag/浏览器/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0c5c4c5e").then(next)
    },
    meta: {"pid":"tags","id":"浏览器"}
  },
  {
    path: "/tag/浏览器/index.html",
    redirect: "/tag/浏览器/"
  },
  {
    name: "v-1c98b280",
    path: "/tag/洋葱模型/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1c98b280").then(next)
    },
    meta: {"pid":"tags","id":"洋葱模型"}
  },
  {
    path: "/tag/洋葱模型/index.html",
    redirect: "/tag/洋葱模型/"
  },
  {
    name: "v-184d5f86",
    path: "/tag/HTTP/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-184d5f86").then(next)
    },
    meta: {"pid":"tags","id":"HTTP"}
  },
  {
    path: "/tag/HTTP/index.html",
    redirect: "/tag/HTTP/"
  },
  {
    name: "v-b6f5cd0c",
    path: "/tag/类型/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-b6f5cd0c").then(next)
    },
    meta: {"pid":"tags","id":"类型"}
  },
  {
    path: "/tag/类型/index.html",
    redirect: "/tag/类型/"
  },
  {
    name: "v-5a4cdae8",
    path: "/tag/类型推论和类型断言/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5a4cdae8").then(next)
    },
    meta: {"pid":"tags","id":"类型推论和类型断言"}
  },
  {
    path: "/tag/类型推论和类型断言/index.html",
    redirect: "/tag/类型推论和类型断言/"
  },
  {
    name: "v-6e72c1b9",
    path: "/tag/组件通信/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-6e72c1b9").then(next)
    },
    meta: {"pid":"tags","id":"组件通信"}
  },
  {
    path: "/tag/组件通信/index.html",
    redirect: "/tag/组件通信/"
  },
  {
    name: "v-047eaeee",
    path: "/tag/路由守卫/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-047eaeee").then(next)
    },
    meta: {"pid":"tags","id":"路由守卫"}
  },
  {
    path: "/tag/路由守卫/index.html",
    redirect: "/tag/路由守卫/"
  },
  {
    name: "v-712b18d6",
    path: "/tag/vue2和vue3的区别/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-712b18d6").then(next)
    },
    meta: {"pid":"tags","id":"vue2和vue3的区别"}
  },
  {
    path: "/tag/vue2和vue3的区别/index.html",
    redirect: "/tag/vue2和vue3的区别/"
  },
  {
    name: "v-7dd2b672",
    path: "/tag/index/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7dd2b672").then(next)
    },
    meta: {"pid":"tags","id":"index"}
  },
  {
    path: "/tag/index/index.html",
    redirect: "/tag/index/"
  },
  {
    name: "v-1b42b88c",
    path: "/tag/-XSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1b42b88c").then(next)
    },
    meta: {"pid":"tags","id":"-XSS"}
  },
  {
    path: "/tag/-XSS/index.html",
    redirect: "/tag/-XSS/"
  },
  {
    name: "v-0a2b6856",
    path: "/tag/路由带参/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0a2b6856").then(next)
    },
    meta: {"pid":"tags","id":"路由带参"}
  },
  {
    path: "/tag/路由带参/index.html",
    redirect: "/tag/路由带参/"
  },
  {
    name: "v-1bc5c70c",
    path: "/tag/-扁平化/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1bc5c70c").then(next)
    },
    meta: {"pid":"tags","id":"-扁平化"}
  },
  {
    path: "/tag/-扁平化/index.html",
    redirect: "/tag/-扁平化/"
  },
  {
    name: "v-0b58b14a",
    path: "/tag/手写题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0b58b14a").then(next)
    },
    meta: {"pid":"tags","id":"手写题"}
  },
  {
    path: "/tag/手写题/index.html",
    redirect: "/tag/手写题/"
  },
  {
    name: "v-9b8daaa2",
    path: "/tag/-大文件上传/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-9b8daaa2").then(next)
    },
    meta: {"pid":"tags","id":"-大文件上传"}
  },
  {
    path: "/tag/-大文件上传/index.html",
    redirect: "/tag/-大文件上传/"
  },
  {
    name: "v-599a76af",
    path: "/categories/字节青训营笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-599a76af").then(next)
    },
    meta: {"pid":"categories","id":"字节青训营笔记"}
  },
  {
    path: "/categories/字节青训营笔记/index.html",
    redirect: "/categories/字节青训营笔记/"
  },
  {
    name: "v-7eff4a05",
    path: "/categories/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7eff4a05").then(next)
    },
    meta: {"pid":"categories","id":"ES6"}
  },
  {
    path: "/categories/ES6/index.html",
    redirect: "/categories/ES6/"
  },
  {
    name: "v-7f008cdb",
    path: "/categories/Git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f008cdb").then(next)
    },
    meta: {"pid":"categories","id":"Git"}
  },
  {
    path: "/categories/Git/index.html",
    redirect: "/categories/Git/"
  },
  {
    name: "v-b6345f38",
    path: "/categories/Javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-b6345f38").then(next)
    },
    meta: {"pid":"categories","id":"Javascript"}
  },
  {
    path: "/categories/Javascript/index.html",
    redirect: "/categories/Javascript/"
  },
  {
    name: "v-466f3074",
    path: "/categories/NodeJS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-466f3074").then(next)
    },
    meta: {"pid":"categories","id":"NodeJS"}
  },
  {
    path: "/categories/NodeJS/index.html",
    redirect: "/categories/NodeJS/"
  },
  {
    name: "v-fabcff68",
    path: "/categories/Typescript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-fabcff68").then(next)
    },
    meta: {"pid":"categories","id":"Typescript"}
  },
  {
    path: "/categories/Typescript/index.html",
    redirect: "/categories/Typescript/"
  },
  {
    name: "v-3f0d1106",
    path: "/categories/Vue Series/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-3f0d1106").then(next)
    },
    meta: {"pid":"categories","id":"Vue Series"}
  },
  {
    path: "/categories/Vue Series/index.html",
    redirect: "/categories/Vue Series/"
  },
  {
    name: "v-0a4268d2",
    path: "/categories/浏览器/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-0a4268d2").then(next)
    },
    meta: {"pid":"categories","id":"浏览器"}
  },
  {
    path: "/categories/浏览器/index.html",
    redirect: "/categories/浏览器/"
  },
  {
    name: "v-093ecdbe",
    path: "/categories/手写题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-093ecdbe").then(next)
    },
    meta: {"pid":"categories","id":"手写题"}
  },
  {
    path: "/categories/手写题/index.html",
    redirect: "/categories/手写题/"
  },
  {
    name: "v-172f4c96",
    path: "/categories/面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-172f4c96").then(next)
    },
    meta: {"pid":"categories","id":"面试题"}
  },
  {
    path: "/categories/面试题/index.html",
    redirect: "/categories/面试题/"
  },
  {
    name: "v-57ffccd9",
    path: "/categories/Javascript/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57ffccd9").then(next)
    },
    meta: {"pid":"categories","id":"Javascript"}
  },
  {
    path: "/categories/Javascript/page/2/index.html",
    redirect: "/categories/Javascript/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]