/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "fieemiracle的博客",
  "description": "纸上得来终觉浅，绝知此事要躬行~",
  "base": "/personnal-blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/personnal-blog/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "响应式系统与React|青训营笔记",
      "frontmatter": {
        "title": "响应式系统与React|青训营笔记",
        "date": "2022-08-23T00:00:00.000Z",
        "tags": [
          "青训营笔记"
        ],
        "categories": [
          "字节青训营笔记"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Byte/notes-react.html",
      "relativePath": "handbook/Byte/notes-react.md",
      "key": "v-4e2589a8",
      "path": "/handbook/Byte/notes-react.html",
      "headers": [
        {
          "level": 2,
          "title": "一、React的历史与应用",
          "slug": "一、react的历史与应用"
        },
        {
          "level": 2,
          "title": "二、React的设计思路",
          "slug": "二、react的设计思路"
        },
        {
          "level": 3,
          "title": "1、UI编程的特点：",
          "slug": "_1、ui编程的特点"
        },
        {
          "level": 3,
          "title": "2、设计思路",
          "slug": "_2、设计思路"
        },
        {
          "level": 3,
          "title": "3、组件化",
          "slug": "_3、组件化"
        },
        {
          "level": 3,
          "title": "4、状态归属问题",
          "slug": "_4、状态归属问题"
        },
        {
          "level": 2,
          "title": "三、React（hooks）的写法",
          "slug": "三、react-hooks-的写法"
        },
        {
          "level": 2,
          "title": "四、React的简单实现demo",
          "slug": "四、react的简单实现demo"
        },
        {
          "level": 3,
          "title": "1、React的实现主要解决三个问题：",
          "slug": "_1、react的实现主要解决三个问题"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "fieemiracle",
        "tagline": "纸上得来终觉浅，绝知此事要躬行~",
        "bgImageStyle": {
          "height": "500px"
        },
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-33cba05a",
      "path": "/",
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "javascript中的糖衣语法--Promise对象",
      "frontmatter": {
        "title": "javascript中的糖衣语法--Promise对象",
        "date": "2022-07-19T00:00:00.000Z",
        "tags": [
          "Promise"
        ],
        "categories": [
          "ES6"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/ES6/Promise.html",
      "relativePath": "handbook/ES6/Promise.md",
      "key": "v-fa9d4098",
      "path": "/handbook/ES6/Promise.html",
      "headers": [
        {
          "level": 2,
          "title": "一、Promise的诞生",
          "slug": "一、promise的诞生"
        },
        {
          "level": 3,
          "title": "1、回调地狱",
          "slug": "_1、回调地狱"
        },
        {
          "level": 2,
          "title": "二、Promise的行为",
          "slug": "二、promise的行为"
        },
        {
          "level": 3,
          "title": "1、Promise的语法",
          "slug": "_1、promise的语法"
        },
        {
          "level": 2,
          "title": "2、Promise的方法",
          "slug": "_2、promise的方法"
        },
        {
          "level": 3,
          "title": "（1）Promise.prototype.then()",
          "slug": "_1-promise-prototype-then"
        },
        {
          "level": 3,
          "title": "（2）Promise.prototype.catch()",
          "slug": "_2-promise-prototype-catch"
        },
        {
          "level": 3,
          "title": "（3）Promise.prototype.finally()",
          "slug": "_3-promise-prototype-finally"
        },
        {
          "level": 3,
          "title": "（4）Promise.resolve()",
          "slug": "_4-promise-resolve"
        },
        {
          "level": 3,
          "title": "（5）Promise.reject()",
          "slug": "_5-promise-reject"
        },
        {
          "level": 3,
          "title": "（6）Promise.all()",
          "slug": "_6-promise-all"
        },
        {
          "level": 3,
          "title": "（7）Promise.race()",
          "slug": "_7-promise-race"
        },
        {
          "level": 2,
          "title": "三、Promise的场景",
          "slug": "三、promise的场景"
        },
        {
          "level": 3,
          "title": "1、Ajax请求",
          "slug": "_1、ajax请求"
        },
        {
          "level": 3,
          "title": "2、文件读取",
          "slug": "_2、文件读取"
        },
        {
          "level": 3,
          "title": "3、图片加载",
          "slug": "_3、图片加载"
        },
        {
          "level": 3,
          "title": "4、函数封装",
          "slug": "_4、函数封装"
        },
        {
          "level": 2,
          "title": "四、Promise的短板",
          "slug": "四、promise的短板"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "CSS小知识|青训营笔记",
      "frontmatter": {
        "title": "CSS小知识|青训营笔记",
        "date": "2022-08-23T00:00:00.000Z",
        "tags": [
          "青训营笔记"
        ],
        "categories": [
          "字节青训营笔记"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Byte/CSS.html",
      "relativePath": "handbook/Byte/CSS.md",
      "key": "v-3caecaa8",
      "path": "/handbook/Byte/CSS.html",
      "headers": [
        {
          "level": 2,
          "title": "一、英文超出自动换行",
          "slug": "一、英文超出自动换行"
        },
        {
          "level": 2,
          "title": "二、块级排版上下文",
          "slug": "二、块级排版上下文"
        },
        {
          "level": 2,
          "title": "三、Grid布局",
          "slug": "三、grid布局"
        },
        {
          "level": 2,
          "title": "额外知识--自适应单位",
          "slug": "额外知识-自适应单位"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "扒一扒，javascript中for...in和for...of二者区别细谈",
      "frontmatter": {
        "title": "扒一扒，javascript中for...in和for...of二者区别细谈",
        "date": "2022-07-29T00:00:00.000Z",
        "tags": [
          "for-of-in"
        ],
        "categories": [
          "ES6"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/ES6/for-in-of.html",
      "relativePath": "handbook/ES6/for-in-of.md",
      "key": "v-04c3f5f4",
      "path": "/handbook/ES6/for-in-of.html",
      "headers": [
        {
          "level": 2,
          "title": "知识角落",
          "slug": "知识角落"
        },
        {
          "level": 2,
          "title": "一、for...in",
          "slug": "一、for-in"
        },
        {
          "level": 3,
          "title": "for...in语法",
          "slug": "for-in语法"
        },
        {
          "level": 3,
          "title": "1、for...in遍历数组",
          "slug": "_1、for-in遍历数组"
        },
        {
          "level": 3,
          "title": "2、for...in遍历字符串",
          "slug": "_2、for-in遍历字符串"
        },
        {
          "level": 3,
          "title": "3、for...in遍历对象",
          "slug": "_3、for-in遍历对象"
        },
        {
          "level": 3,
          "title": "4、hasOwnProperty（）方法",
          "slug": "_4、hasownproperty-方法"
        },
        {
          "level": 2,
          "title": "二、for...of",
          "slug": "二、for-of"
        },
        {
          "level": 3,
          "title": "for...of语法",
          "slug": "for-of语法"
        },
        {
          "level": 3,
          "title": "1、for...of遍历数组/字符串",
          "slug": "_1、for-of遍历数组-字符串"
        },
        {
          "level": 3,
          "title": "2、for...of遍历对象",
          "slug": "_2、for-of遍历对象"
        },
        {
          "level": 3,
          "title": "3、for...of遍历Map/Set",
          "slug": "_3、for-of遍历map-set"
        },
        {
          "level": 2,
          "title": "三、区别囊括",
          "slug": "三、区别囊括"
        },
        {
          "level": 3,
          "title": "1、for...in",
          "slug": "_1、for-in"
        },
        {
          "level": 3,
          "title": "2、for...of",
          "slug": "_2、for-of"
        },
        {
          "level": 2,
          "title": "四、小贴士",
          "slug": "四、小贴士"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "消灭异步回调，还得是async-await",
      "frontmatter": {
        "title": "消灭异步回调，还得是async-await",
        "date": "2022-07-20T00:00:00.000Z",
        "tags": [
          "async-await"
        ],
        "categories": [
          "ES6"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/ES6/async-await.html",
      "relativePath": "handbook/ES6/async-await.md",
      "key": "v-29052a20",
      "path": "/handbook/ES6/async-await.html",
      "headers": [
        {
          "level": 2,
          "title": "一、走进Async-await原理",
          "slug": "一、走进async-await原理"
        },
        {
          "level": 3,
          "title": "1、原理1",
          "slug": "_1、原理1"
        },
        {
          "level": 3,
          "title": "2、原理2",
          "slug": "_2、原理2"
        },
        {
          "level": 3,
          "title": "3、原理3",
          "slug": "_3、原理3"
        },
        {
          "level": 3,
          "title": "4、原理4",
          "slug": "_4、原理4"
        },
        {
          "level": 2,
          "title": "二、深入Async-await规则",
          "slug": "二、深入async-await规则"
        },
        {
          "level": 3,
          "title": "1、async封装Promise",
          "slug": "_1、async封装promise"
        },
        {
          "level": 3,
          "title": "2、await相当于then",
          "slug": "_2、await相当于then"
        },
        {
          "level": 3,
          "title": "3、多个await时，按时序执行",
          "slug": "_3、多个await时-按时序执行"
        },
        {
          "level": 3,
          "title": "4、try…catch相当于catch",
          "slug": "_4、try-catch相当于catch"
        },
        {
          "level": 2,
          "title": "三、解析Async-await语法",
          "slug": "三、解析async-await语法"
        },
        {
          "level": 2,
          "title": "四、拓展Async-await应用",
          "slug": "四、拓展async-await应用"
        },
        {
          "level": 3,
          "title": "1、场景1",
          "slug": "_1、场景1"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "我这样实现Promise",
      "frontmatter": {
        "title": "我这样实现Promise",
        "date": "2022-11-19T00:00:00.000Z",
        "tags": [
          "Promise"
        ],
        "categories": [
          "ES6"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/ES6/hand-promise.html",
      "relativePath": "handbook/ES6/hand-promise.md",
      "key": "v-34526722",
      "path": "/handbook/ES6/hand-promise.html",
      "headers": [
        {
          "level": 2,
          "title": "一、剖析Promise的基础框架",
          "slug": "一、剖析promise的基础框架"
        },
        {
          "level": 2,
          "title": "二、实现Promsie中两个类型为函数的形参",
          "slug": "二、实现promsie中两个类型为函数的形参"
        },
        {
          "level": 3,
          "title": "1、Promise的三种状态",
          "slug": "_1、promise的三种状态"
        },
        {
          "level": 3,
          "title": "2、Promise的两个类型为函数的形参",
          "slug": "_2、promise的两个类型为函数的形参"
        },
        {
          "level": 2,
          "title": "三、实现.then",
          "slug": "三、实现-then"
        },
        {
          "level": 2,
          "title": "四、实现.catch",
          "slug": "四、实现-catch"
        },
        {
          "level": 2,
          "title": "五、测试",
          "slug": "五、测试"
        },
        {
          "level": 3,
          "title": "1、resolve",
          "slug": "_1、resolve"
        },
        {
          "level": 3,
          "title": "2、reject",
          "slug": "_2、reject"
        },
        {
          "level": 3,
          "title": "3、.then",
          "slug": "_3、-then"
        },
        {
          "level": 3,
          "title": "4、.catch",
          "slug": "_4、-catch"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "工欲善其事，必先利其器（Git）",
      "frontmatter": {
        "title": "工欲善其事，必先利其器（Git）",
        "date": "2022-11-27T00:00:00.000Z",
        "tags": [
          "Git"
        ],
        "categories": [
          "Git"
        ]
      },
      "regularPath": "/handbook/Git/git.html",
      "relativePath": "handbook/Git/git.md",
      "key": "v-2f587472",
      "path": "/handbook/Git/git.html",
      "headers": [
        {
          "level": 2,
          "title": "highlight: a11y-dark\ntheme: scrolls-light",
          "slug": "highlight-a11y-darktheme-scrolls-light"
        },
        {
          "level": 2,
          "title": "一、了解Git",
          "slug": "一、了解git"
        },
        {
          "level": 2,
          "title": "二、Git创建仓库",
          "slug": "二、git创建仓库"
        },
        {
          "level": 2,
          "title": "三、Git查看更改",
          "slug": "三、git查看更改"
        },
        {
          "level": 2,
          "title": "四、Git撤销",
          "slug": "四、git撤销"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "这个冬天，一起认识Generator函数",
      "frontmatter": {
        "title": "这个冬天，一起认识Generator函数",
        "date": "2022-12-01T00:00:00.000Z",
        "tags": [
          "Generator"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/handbook/ES6/generator.html",
      "relativePath": "handbook/ES6/generator.md",
      "key": "v-7396af44",
      "path": "/handbook/ES6/generator.html",
      "headers": [
        {
          "level": 2,
          "title": "theme: fancy\nhighlight: a11y-dark",
          "slug": "theme-fancyhighlight-a11y-dark"
        },
        {
          "level": 2,
          "title": "一、什么是Generator函数？",
          "slug": "一、什么是generator函数"
        },
        {
          "level": 3,
          "title": "1、基本语法",
          "slug": "_1、基本语法"
        },
        {
          "level": 3,
          "title": "2、yield表达式&&next方法",
          "slug": "_2、yield表达式-next方法"
        },
        {
          "level": 3,
          "title": "3、中间件next()",
          "slug": "_3、中间件next"
        },
        {
          "level": 3,
          "title": "4、作为对象的属性",
          "slug": "_4、作为对象的属性"
        },
        {
          "level": 3,
          "title": "5、this指向",
          "slug": "_5、this指向"
        },
        {
          "level": 3,
          "title": "6、与构造函数相比",
          "slug": "_6、与构造函数相比"
        },
        {
          "level": 3,
          "title": "7、与Async-Await相比",
          "slug": "_7、与async-await相比"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "你真的不知道的javascript",
      "frontmatter": {
        "title": "你真的不知道的javascript",
        "date": "2022-11-27T00:00:00.000Z",
        "tags": [
          "javascript"
        ],
        "categories": [
          "Javascript"
        ]
      },
      "regularPath": "/handbook/Javascript/NaN.html",
      "relativePath": "handbook/Javascript/NaN.md",
      "key": "v-740c6c70",
      "path": "/handbook/Javascript/NaN.html",
      "headers": [
        {
          "level": 2,
          "title": "一、isNaN和Number.isNaN",
          "slug": "一、isnan和number-isnan"
        },
        {
          "level": 3,
          "title": "（1）isNaN",
          "slug": "_1-isnan"
        },
        {
          "level": 3,
          "title": "（2）Number.isNaN",
          "slug": "_2-number-isnan"
        },
        {
          "level": 2,
          "title": "二、js引擎内部的装箱与拆箱",
          "slug": "二、js引擎内部的装箱与拆箱"
        },
        {
          "level": 3,
          "title": "1、装箱",
          "slug": "_1、装箱"
        },
        {
          "level": 3,
          "title": "2、拆箱",
          "slug": "_2、拆箱"
        },
        {
          "level": 2,
          "title": "三、typeof null？",
          "slug": "三、typeof-null"
        },
        {
          "level": 2,
          "title": "四、js隐式转换规则",
          "slug": "四、js隐式转换规则"
        },
        {
          "level": 3,
          "title": "1、运算符",
          "slug": "_1、运算符"
        },
        {
          "level": 3,
          "title": "2、等号",
          "slug": "_2、等号"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "不可不说的Array.xxx（）（上）",
      "frontmatter": {
        "title": "不可不说的Array.xxx（）（上）",
        "date": "2022-07-15T00:00:00.000Z",
        "tags": [
          "数组"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/Array.html",
      "relativePath": "handbook/Javascript/Array.md",
      "key": "v-89b357f0",
      "path": "/handbook/Javascript/Array.html",
      "headers": [
        {
          "level": 2,
          "title": "一、必须熟悉的数组迭代方法",
          "slug": "一、必须熟悉的数组迭代方法"
        },
        {
          "level": 3,
          "title": "参数意义",
          "slug": "参数意义"
        },
        {
          "level": 3,
          "title": "1、Array.forEach(value,index,array）",
          "slug": "_1、array-foreach-value-index-array"
        },
        {
          "level": 3,
          "title": "2、Array.map(value,index,array)",
          "slug": "_2、array-map-value-index-array"
        },
        {
          "level": 3,
          "title": "3、Array.filter(value,index,array)",
          "slug": "_3、array-filter-value-index-array"
        },
        {
          "level": 3,
          "title": "4、Array.reduce(total, value, index, array)",
          "slug": "_4、array-reduce-total-value-index-array"
        },
        {
          "level": 3,
          "title": "5、Array.reduceRight(total, value, index, array)",
          "slug": "_5、array-reduceright-total-value-index-array"
        },
        {
          "level": 3,
          "title": "6、Array.every(value, index, array)",
          "slug": "_6、array-every-value-index-array"
        },
        {
          "level": 3,
          "title": "7、Array.some(value, index, array)",
          "slug": "_7、array-some-value-index-array"
        },
        {
          "level": 3,
          "title": "8、Array.indexOf(item, start)",
          "slug": "_8、array-indexof-item-start"
        },
        {
          "level": 3,
          "title": "9、Array.lastIndexOf(item, start)",
          "slug": "_9、array-lastindexof-item-start"
        },
        {
          "level": 3,
          "title": "10、Array.find(value, index, array)",
          "slug": "_10、array-find-value-index-array"
        },
        {
          "level": 3,
          "title": "11、Array.findIndex(value, index, array)",
          "slug": "_11、array-findindex-value-index-array"
        },
        {
          "level": 2,
          "title": "二、必须会的简单方法",
          "slug": "二、必须会的简单方法"
        },
        {
          "level": 3,
          "title": "1、反转",
          "slug": "_1、反转"
        },
        {
          "level": 3,
          "title": "2、切割",
          "slug": "_2、切割"
        },
        {
          "level": 3,
          "title": "3、类型转换",
          "slug": "_3、类型转换"
        },
        {
          "level": 3,
          "title": "4、排序",
          "slug": "_4、排序"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "javascript--闭包知多少",
      "frontmatter": {
        "title": "javascript--闭包知多少",
        "date": "2022-07-14T00:00:00.000Z",
        "tags": [
          "闭包"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/clourse.html",
      "relativePath": "handbook/Javascript/clourse.md",
      "key": "v-1e72e1f0",
      "path": "/handbook/Javascript/clourse.html",
      "headers": [
        {
          "level": 2,
          "title": "一、闭包的概念",
          "slug": "一、闭包的概念"
        },
        {
          "level": 2,
          "title": "二、闭包的作用",
          "slug": "二、闭包的作用"
        },
        {
          "level": 2,
          "title": "三、闭包的缺陷",
          "slug": "三、闭包的缺陷"
        },
        {
          "level": 3,
          "title": "（1）内存泄漏",
          "slug": "_1-内存泄漏"
        },
        {
          "level": 2,
          "title": "四、闭包的应用场景",
          "slug": "四、闭包的应用场景"
        },
        {
          "level": 3,
          "title": "（1）定时器",
          "slug": "_1-定时器"
        },
        {
          "level": 3,
          "title": "（2）事件监听器",
          "slug": "_2-事件监听器"
        },
        {
          "level": 3,
          "title": "（3）return一个函数",
          "slug": "_3-return一个函数"
        },
        {
          "level": 3,
          "title": "（4）异步编程",
          "slug": "_4-异步编程"
        },
        {
          "level": 3,
          "title": "（5）IIFE模式",
          "slug": "_5-iife模式"
        },
        {
          "level": 3,
          "title": "（6）for循环和闭包",
          "slug": "_6-for循环和闭包"
        },
        {
          "level": 3,
          "title": "（7）块作用域和闭包",
          "slug": "_7-块作用域和闭包"
        },
        {
          "level": 3,
          "title": "（8）函数作为参数",
          "slug": "_8-函数作为参数"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "那就聊聊深拷贝和浅拷贝",
      "frontmatter": {
        "title": "那就聊聊深拷贝和浅拷贝",
        "date": "2022-10-11T00:00:00.000Z",
        "tags": [
          "深浅拷贝"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/copy.html",
      "relativePath": "handbook/Javascript/copy.md",
      "key": "v-415673b4",
      "path": "/handbook/Javascript/copy.html",
      "headers": [
        {
          "level": 2,
          "title": "一、浅拷贝",
          "slug": "一、浅拷贝"
        },
        {
          "level": 3,
          "title": "1、什么是浅拷贝？",
          "slug": "_1、什么是浅拷贝"
        },
        {
          "level": 3,
          "title": "2、如何实现浅拷贝？",
          "slug": "_2、如何实现浅拷贝"
        },
        {
          "level": 2,
          "title": "二、深拷贝",
          "slug": "二、深拷贝"
        },
        {
          "level": 3,
          "title": "1、什么是深拷贝？",
          "slug": "_1、什么是深拷贝"
        },
        {
          "level": 3,
          "title": "2、如何实现深拷贝？",
          "slug": "_2、如何实现深拷贝"
        },
        {
          "level": 2,
          "title": "三、手写浅拷贝",
          "slug": "三、手写浅拷贝"
        },
        {
          "level": 2,
          "title": "四、手写深拷贝",
          "slug": "四、手写深拷贝"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "快来学习javascript设计模式",
      "frontmatter": {
        "title": "快来学习javascript设计模式",
        "date": "2022-12-04T00:00:00.000Z",
        "tags": [
          "设计模式"
        ],
        "categories": [
          "Javascript"
        ]
      },
      "regularPath": "/handbook/Javascript/design-mode.html",
      "relativePath": "handbook/Javascript/design-mode.md",
      "key": "v-3cfeb528",
      "path": "/handbook/Javascript/design-mode.html",
      "headers": [
        {
          "level": 2,
          "title": "highlight: a11y-dark\ntheme: healer-readable",
          "slug": "highlight-a11y-darktheme-healer-readable"
        },
        {
          "level": 2,
          "title": "一、工厂模式",
          "slug": "一、工厂模式"
        },
        {
          "level": 3,
          "title": "（1）什么是工厂模式？",
          "slug": "_1-什么是工厂模式"
        },
        {
          "level": 3,
          "title": "（2）核心思想",
          "slug": "_2-核心思想"
        },
        {
          "level": 3,
          "title": "（3）关于工厂模式",
          "slug": "_3-关于工厂模式"
        },
        {
          "level": 2,
          "title": "二、单例模式",
          "slug": "二、单例模式"
        },
        {
          "level": 3,
          "title": "（1）什么是单例模式？",
          "slug": "_1-什么是单例模式"
        },
        {
          "level": 3,
          "title": "（2）核心思想",
          "slug": "_2-核心思想-2"
        },
        {
          "level": 3,
          "title": "（3）关于单例模式",
          "slug": "_3-关于单例模式"
        },
        {
          "level": 2,
          "title": "三、装饰器模式",
          "slug": "三、装饰器模式"
        },
        {
          "level": 3,
          "title": "（1）什么是装饰器模式？",
          "slug": "_1-什么是装饰器模式"
        },
        {
          "level": 3,
          "title": "（2）核心思想",
          "slug": "_2-核心思想-3"
        },
        {
          "level": 3,
          "title": "（3）关于装饰器模式",
          "slug": "_3-关于装饰器模式"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "挑战一夏，浏览器事件循环（Event Loop）清凉来袭",
      "frontmatter": {
        "title": "挑战一夏，浏览器事件循环（Event Loop）清凉来袭",
        "date": "2022-07-22T00:00:00.000Z",
        "tags": [
          "浏览器的事件循环"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/eventloop.html",
      "relativePath": "handbook/Javascript/eventloop.md",
      "key": "v-46361b30",
      "path": "/handbook/Javascript/eventloop.html",
      "headers": [
        {
          "level": 2,
          "title": "写在前面",
          "slug": "写在前面"
        },
        {
          "level": 2,
          "title": "一、准备阶段",
          "slug": "一、准备阶段"
        },
        {
          "level": 3,
          "title": "1、进程和线程？",
          "slug": "_1、进程和线程"
        },
        {
          "level": 3,
          "title": "2、调用栈（执行栈）？",
          "slug": "_2、调用栈-执行栈"
        },
        {
          "level": 3,
          "title": "3、javascript单线程的好处？",
          "slug": "_3、javascript单线程的好处"
        },
        {
          "level": 3,
          "title": "4、浏览器的事件循环(Event Loop)？",
          "slug": "_4、浏览器的事件循环-event-loop"
        },
        {
          "level": 3,
          "title": "5、宏任务和微任务？",
          "slug": "_5、宏任务和微任务"
        },
        {
          "level": 3,
          "title": "6、最终执行顺序？",
          "slug": "_6、最终执行顺序"
        },
        {
          "level": 2,
          "title": "二、试水阶段",
          "slug": "二、试水阶段"
        },
        {
          "level": 3,
          "title": "1、牛刀小试1--定时器",
          "slug": "_1、牛刀小试1-定时器"
        },
        {
          "level": 3,
          "title": "2、牛刀小试2-Promise",
          "slug": "_2、牛刀小试2-promise"
        },
        {
          "level": 3,
          "title": "3、牛刀小试3-Async-await",
          "slug": "_3、牛刀小试3-async-await"
        },
        {
          "level": 2,
          "title": "三、进阶阶段",
          "slug": "三、进阶阶段"
        },
        {
          "level": 3,
          "title": "1、题目一",
          "slug": "_1、题目一"
        },
        {
          "level": 3,
          "title": "2、题目二",
          "slug": "_2、题目二"
        },
        {
          "level": 2,
          "title": "四、思考阶段",
          "slug": "四、思考阶段"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "跨域小知识，小白看了都说悟了",
      "frontmatter": {
        "title": "跨域小知识，小白看了都说悟了",
        "date": "2022-10-27T00:00:00.000Z",
        "tags": [
          "跨域"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/cross.html",
      "relativePath": "handbook/Javascript/cross.md",
      "key": "v-448482b0",
      "path": "/handbook/Javascript/cross.html",
      "headers": [
        {
          "level": 2,
          "title": "一、跨域的导火线？",
          "slug": "一、跨域的导火线"
        },
        {
          "level": 2,
          "title": "二、跨域？",
          "slug": "二、跨域"
        },
        {
          "level": 2,
          "title": "三、跨域通常发生在？",
          "slug": "三、跨域通常发生在"
        },
        {
          "level": 2,
          "title": "四、解决跨域方案？",
          "slug": "四、解决跨域方案"
        },
        {
          "level": 3,
          "title": "1、JSONP",
          "slug": "_1、jsonp"
        },
        {
          "level": 3,
          "title": "2、Cors",
          "slug": "_2、cors"
        },
        {
          "level": 3,
          "title": "3、node的Proxy",
          "slug": "_3、node的proxy"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "会用new还不够，还得知道它到底做了什么",
      "frontmatter": {
        "title": "会用new还不够，还得知道它到底做了什么",
        "date": "2022-10-24T00:00:00.000Z",
        "tags": [
          "new原理"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/new.html",
      "relativePath": "handbook/Javascript/new.md",
      "key": "v-5a59ae30",
      "path": "/handbook/Javascript/new.html",
      "headers": [
        {
          "level": 2,
          "title": "一、new做了哪些事？",
          "slug": "一、new做了哪些事"
        },
        {
          "level": 2,
          "title": "二、返回不同类型时有哪些表现？",
          "slug": "二、返回不同类型时有哪些表现"
        },
        {
          "level": 2,
          "title": "三、手写new的实现原理?",
          "slug": "三、手写new的实现原理"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "一盏茶的功夫，拿捏作用域&作用域链",
      "frontmatter": {
        "title": "一盏茶的功夫，拿捏作用域&作用域链",
        "date": "2022-07-04T00:00:00.000Z",
        "tags": [
          "作用域和作用域链"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/scope.html",
      "relativePath": "handbook/Javascript/scope.md",
      "key": "v-c94833b0",
      "path": "/handbook/Javascript/scope.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "一、作用域(scope)",
          "slug": "一、作用域-scope"
        },
        {
          "level": 3,
          "title": "1、作用域的分类",
          "slug": "_1、作用域的分类"
        },
        {
          "level": 2,
          "title": "二、预编译",
          "slug": "二、预编译"
        },
        {
          "level": 3,
          "title": "1. 发生在代码执行之前",
          "slug": "_1-发生在代码执行之前"
        },
        {
          "level": 3,
          "title": "2.发生在函数执行之前",
          "slug": "_2-发生在函数执行之前"
        },
        {
          "level": 3,
          "title": "3.发生在全局（内层作用域可以访问外层作用域）",
          "slug": "_3-发生在全局-内层作用域可以访问外层作用域"
        },
        {
          "level": 2,
          "title": "三、作用域链",
          "slug": "三、作用域链"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "关于Javascript类型转换，你该了解这些",
      "frontmatter": {
        "title": "关于Javascript类型转换，你该了解这些",
        "date": "2022-08-11T00:00:00.000Z",
        "tags": [
          "类型转换"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/type.html",
      "relativePath": "handbook/Javascript/type.md",
      "key": "v-18ae93ea",
      "path": "/handbook/Javascript/type.html",
      "headers": [
        {
          "level": 2,
          "title": "一、将其他数据类型转换为原始数据类型",
          "slug": "一、将其他数据类型转换为原始数据类型"
        },
        {
          "level": 3,
          "title": "1、将其他数据类型转换为Boolean",
          "slug": "_1、将其他数据类型转换为boolean"
        },
        {
          "level": 3,
          "title": "2、将其他数据类型转换为Number",
          "slug": "_2、将其他数据类型转换为number"
        },
        {
          "level": 3,
          "title": "3、将其他数据类型转换为String",
          "slug": "_3、将其他数据类型转换为string"
        },
        {
          "level": 2,
          "title": "二、将原始数据类型转换为Object",
          "slug": "二、将原始数据类型转换为object"
        },
        {
          "level": 2,
          "title": "三、将Object转换为String/Number",
          "slug": "三、将object转换为string-number"
        },
        {
          "level": 3,
          "title": "1、将Object转换为String",
          "slug": "_1、将object转换为string"
        },
        {
          "level": 3,
          "title": "2、将Object转换为Number",
          "slug": "_2、将object转换为number"
        },
        {
          "level": 3,
          "title": "3、将Object转换为JSON",
          "slug": "_3、将object转换为json"
        },
        {
          "level": 2,
          "title": "四、运算符与隐式转换",
          "slug": "四、运算符与隐式转换"
        },
        {
          "level": 3,
          "title": "1、一元操作符",
          "slug": "_1、一元操作符"
        },
        {
          "level": 3,
          "title": "2、二元操作符",
          "slug": "_2、二元操作符"
        },
        {
          "level": 3,
          "title": "3、二元运算符",
          "slug": "_3、二元运算符"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "解析JavaScript--关键字this",
      "frontmatter": {
        "title": "解析JavaScript--关键字this",
        "date": "2022-07-12T00:00:00.000Z",
        "tags": [
          "关键字this"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/this.html",
      "relativePath": "handbook/Javascript/this.md",
      "key": "v-b020dfbc",
      "path": "/handbook/Javascript/this.html",
      "headers": [
        {
          "level": 2,
          "title": "Tips",
          "slug": "tips"
        },
        {
          "level": 2,
          "title": "一、this的绑定规则",
          "slug": "一、this的绑定规则"
        },
        {
          "level": 3,
          "title": "1、默认绑定",
          "slug": "_1、默认绑定"
        },
        {
          "level": 3,
          "title": "2、隐式绑定",
          "slug": "_2、隐式绑定"
        },
        {
          "level": 3,
          "title": "3、隐式丢失",
          "slug": "_3、隐式丢失"
        },
        {
          "level": 3,
          "title": "4、显式绑定",
          "slug": "_4、显式绑定"
        },
        {
          "level": 2,
          "title": "二、this的指向",
          "slug": "二、this的指向"
        },
        {
          "level": 3,
          "title": "1、函数的普通调用",
          "slug": "_1、函数的普通调用"
        },
        {
          "level": 3,
          "title": "2、构造函数",
          "slug": "_2、构造函数"
        },
        {
          "level": 3,
          "title": "3、箭头函数",
          "slug": "_3、箭头函数"
        },
        {
          "level": 2,
          "title": "三、改变this的指向",
          "slug": "三、改变this的指向"
        },
        {
          "level": 3,
          "title": "1、使用 ES6 的箭头函数",
          "slug": "_1、使用-es6-的箭头函数"
        },
        {
          "level": 3,
          "title": "2、在函数内部使用 _this = this",
          "slug": "_2、在函数内部使用-this-this"
        },
        {
          "level": 3,
          "title": "3、使用 apply()、call()、bind()",
          "slug": "_3、使用-apply-、call-、bind"
        },
        {
          "level": 3,
          "title": "4、new 实例化一个对象",
          "slug": "_4、new-实例化一个对象"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "解析javascript--原型+原型链",
      "frontmatter": {
        "title": "解析javascript--原型+原型链",
        "date": "2022-07-09T00:00:00.000Z",
        "tags": [
          "原型和原型链"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/prototype.html",
      "relativePath": "handbook/Javascript/prototype.md",
      "key": "v-64b915e8",
      "path": "/handbook/Javascript/prototype.html",
      "headers": [
        {
          "level": 2,
          "title": "写在前面",
          "slug": "写在前面"
        },
        {
          "level": 2,
          "title": "一、先掌握",
          "slug": "一、先掌握"
        },
        {
          "level": 3,
          "title": "1、浅剖析--函数中的原型对象",
          "slug": "_1、浅剖析-函数中的原型对象"
        },
        {
          "level": 3,
          "title": "2、深剖析--理解原型对象",
          "slug": "_2、深剖析-理解原型对象"
        },
        {
          "level": 2,
          "title": "二、再分析",
          "slug": "二、再分析"
        },
        {
          "level": 2,
          "title": "三、后拓展",
          "slug": "三、后拓展"
        },
        {
          "level": 3,
          "title": "1、原型的增删改查",
          "slug": "_1、原型的增删改查"
        },
        {
          "level": 3,
          "title": "2、对象的原型",
          "slug": "_2、对象的原型"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "前端路由也能像vue-router一样香",
      "frontmatter": {
        "title": "前端路由也能像vue-router一样香",
        "date": "2022-09-14T00:00:00.000Z",
        "tags": [
          "前端路由"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/web-router.html",
      "relativePath": "handbook/Javascript/web-router.md",
      "key": "v-2534b6da",
      "path": "/handbook/Javascript/web-router.html",
      "headers": [
        {
          "level": 2,
          "title": "一、先看看vue-router的效果",
          "slug": "一、先看看vue-router的效果"
        },
        {
          "level": 2,
          "title": "二、什么是前端路由",
          "slug": "二、什么是前端路由"
        },
        {
          "level": 2,
          "title": "三、前端路由解决的两个主要问题",
          "slug": "三、前端路由解决的两个主要问题"
        },
        {
          "level": 2,
          "title": "四、实现前端路由的方案",
          "slug": "四、实现前端路由的方案"
        },
        {
          "level": 3,
          "title": "1、hash模式",
          "slug": "_1、hash模式"
        },
        {
          "level": 3,
          "title": "2、history模式",
          "slug": "_2、history模式"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "浏览器从输入url到页面渲染发生了什么（今生）",
      "frontmatter": {
        "title": "浏览器从输入url到页面渲染发生了什么（今生）",
        "date": "2022-10-18T00:00:00.000Z",
        "tags": [
          "url",
          "浏览器"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/url-render-bot.html",
      "relativePath": "handbook/Javascript/url-render-bot.md",
      "key": "v-66562fc2",
      "path": "/handbook/Javascript/url-render-bot.html",
      "headers": [
        {
          "level": 2,
          "title": "一、渲染页面",
          "slug": "一、渲染页面"
        },
        {
          "level": 2,
          "title": "二、渲染",
          "slug": "二、渲染"
        },
        {
          "level": 2,
          "title": "三、回流（重排）",
          "slug": "三、回流-重排"
        },
        {
          "level": 3,
          "title": "1、发生重排的操作",
          "slug": "_1、发生重排的操作"
        },
        {
          "level": 3,
          "title": "2、减少重排操作",
          "slug": "_2、减少重排操作"
        },
        {
          "level": 2,
          "title": "四、重绘",
          "slug": "四、重绘"
        },
        {
          "level": 2,
          "title": "五、浏览器的优化",
          "slug": "五、浏览器的优化"
        },
        {
          "level": 2,
          "title": "六、什么情况下会发生重排？",
          "slug": "六、什么情况下会发生重排"
        },
        {
          "level": 3,
          "title": "（1）导致回流的操作",
          "slug": "_1-导致回流的操作"
        },
        {
          "level": 3,
          "title": "（2）导致回流的属性和方法",
          "slug": "_2-导致回流的属性和方法"
        },
        {
          "level": 3,
          "title": "（3）导致回流的结构变化",
          "slug": "_3-导致回流的结构变化"
        },
        {
          "level": 2,
          "title": "七、如何减少页面重排与重绘？",
          "slug": "七、如何减少页面重排与重绘"
        },
        {
          "level": 3,
          "title": "1、CSS",
          "slug": "_1、css"
        },
        {
          "level": 3,
          "title": "2、JavaScript",
          "slug": "_2、javascript"
        },
        {
          "level": 2,
          "title": "八、牛刀小试",
          "slug": "八、牛刀小试"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "浏览器从输入url到页面渲染发生了什么（前世）",
      "frontmatter": {
        "title": "浏览器从输入url到页面渲染发生了什么（前世）",
        "date": "2022-10-14T00:00:00.000Z",
        "tags": [
          "url",
          "浏览器"
        ],
        "categories": [
          "Javascript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Javascript/url-render-top.html",
      "relativePath": "handbook/Javascript/url-render-top.md",
      "key": "v-a7e376b4",
      "path": "/handbook/Javascript/url-render-top.html",
      "headers": [
        {
          "level": 2,
          "title": "一、DNS解析",
          "slug": "一、dns解析"
        },
        {
          "level": 2,
          "title": "二、HTTP建立连接（三次握手四次挥手）",
          "slug": "二、http建立连接-三次握手四次挥手"
        },
        {
          "level": 3,
          "title": "1、TCP三次握手",
          "slug": "_1、tcp三次握手"
        },
        {
          "level": 3,
          "title": "2、为什么一定是三次握手？",
          "slug": "_2、为什么一定是三次握手"
        },
        {
          "level": 3,
          "title": "3、TCP四次挥手",
          "slug": "_3、tcp四次挥手"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "如果你一层一层一层地剥开洋葱模型，你会明白",
      "frontmatter": {
        "title": "如果你一层一层一层地剥开洋葱模型，你会明白",
        "date": "2022-07-26T00:00:00.000Z",
        "tags": [
          "洋葱模型"
        ],
        "categories": [
          "NodeJS"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/NodeJS/onion.html",
      "relativePath": "handbook/NodeJS/onion.md",
      "key": "v-1230f3c8",
      "path": "/handbook/NodeJS/onion.html",
      "headers": [
        {
          "level": 2,
          "title": "知识卡片",
          "slug": "知识卡片"
        },
        {
          "level": 3,
          "title": "-   koa",
          "slug": "koa"
        },
        {
          "level": 3,
          "title": "-   中间件",
          "slug": "中间件"
        },
        {
          "level": 2,
          "title": "洋葱模型执行过程",
          "slug": "洋葱模型执行过程"
        },
        {
          "level": 2,
          "title": "洋葱模型执行原理",
          "slug": "洋葱模型执行原理"
        },
        {
          "level": 2,
          "title": "洋葱模型存在意义",
          "slug": "洋葱模型存在意义"
        },
        {
          "level": 2,
          "title": "结尾",
          "slug": "结尾"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "关于HTTP，你能侃侃而谈嘛？",
      "frontmatter": {
        "title": "关于HTTP，你能侃侃而谈嘛？",
        "date": "2022-11-18T00:00:00.000Z",
        "tags": [
          "HTTP"
        ],
        "categories": [
          "NodeJS"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/NodeJS/http.html",
      "relativePath": "handbook/NodeJS/http.md",
      "key": "v-81c9c4ec",
      "path": "/handbook/NodeJS/http.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "一、HTTP 0.9",
          "slug": "一、http-0-9"
        },
        {
          "level": 2,
          "title": "二、HTTP 1.0",
          "slug": "二、http-1-0"
        },
        {
          "level": 3,
          "title": "1、引入请求头和响应头",
          "slug": "_1、引入请求头和响应头"
        },
        {
          "level": 3,
          "title": "2、引入状态码/错误码",
          "slug": "_2、引入状态码-错误码"
        },
        {
          "level": 3,
          "title": "3、引入Cache（缓存机制）",
          "slug": "_3、引入cache-缓存机制"
        },
        {
          "level": 2,
          "title": "三、HTTP 2.0",
          "slug": "三、http-2-0"
        },
        {
          "level": 2,
          "title": "四、HTTP 3.0",
          "slug": "四、http-3-0"
        },
        {
          "level": 3,
          "title": "1、面向无连接的UDP 协议（传输层的协议）",
          "slug": "_1、面向无连接的udp-协议-传输层的协议"
        },
        {
          "level": 3,
          "title": "2、QUIC 协议",
          "slug": "_2、quic-协议"
        },
        {
          "level": 2,
          "title": "结尾",
          "slug": "结尾"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "Typescript类型|学习笔记",
      "frontmatter": {
        "title": "Typescript类型|学习笔记",
        "date": "2022-10-09T00:00:00.000Z",
        "tags": [
          "类型"
        ],
        "categories": [
          "Typescript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Typescript/ts-type.html",
      "relativePath": "handbook/Typescript/ts-type.md",
      "key": "v-71ef9468",
      "path": "/handbook/Typescript/ts-type.html",
      "headers": [
        {
          "level": 2,
          "title": "一、认识Typescript",
          "slug": "一、认识typescript"
        },
        {
          "level": 2,
          "title": "二、Typescript优缺点",
          "slug": "二、typescript优缺点"
        },
        {
          "level": 3,
          "title": "1、优点：",
          "slug": "_1、优点"
        },
        {
          "level": 3,
          "title": "2、缺点：",
          "slug": "_2、缺点"
        },
        {
          "level": 2,
          "title": "三、运行Typescript",
          "slug": "三、运行typescript"
        },
        {
          "level": 2,
          "title": "四、基本类型",
          "slug": "四、基本类型"
        },
        {
          "level": 3,
          "title": "1、非Typescript新增类型",
          "slug": "_1、非typescript新增类型"
        },
        {
          "level": 3,
          "title": "2、Typescript新增类型",
          "slug": "_2、typescript新增类型"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "TypeScript类型推论和类型断言",
      "frontmatter": {
        "title": "TypeScript类型推论和类型断言",
        "date": "2022-11-20T00:00:00.000Z",
        "tags": [
          "类型推论和类型断言"
        ],
        "categories": [
          "Typescript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Typescript/judge.html",
      "relativePath": "handbook/Typescript/judge.md",
      "key": "v-4d47a048",
      "path": "/handbook/Typescript/judge.html",
      "headers": [
        {
          "level": 2,
          "title": "一、类型推论",
          "slug": "一、类型推论"
        },
        {
          "level": 3,
          "title": "1、最佳通用类型",
          "slug": "_1、最佳通用类型"
        },
        {
          "level": 3,
          "title": "2、上下文类型",
          "slug": "_2、上下文类型"
        },
        {
          "level": 2,
          "title": "二、类型断言",
          "slug": "二、类型断言"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "组件之间的通信，你会几种？",
      "frontmatter": {
        "title": "组件之间的通信，你会几种？",
        "date": "2022-10-31T00:00:00.000Z",
        "tags": [
          "组件通信"
        ],
        "categories": [
          "Vue Series"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Vue%20Series/communicate.html",
      "relativePath": "handbook/Vue Series/communicate.md",
      "key": "v-bf6ce736",
      "path": "/handbook/Vue%20Series/communicate.html",
      "headers": [
        {
          "level": 2,
          "title": "一、Props",
          "slug": "一、props"
        },
        {
          "level": 2,
          "title": "二、emit",
          "slug": "二、emit"
        },
        {
          "level": 2,
          "title": "三、expose/ref",
          "slug": "三、expose-ref"
        },
        {
          "level": 2,
          "title": "四、provide/inject",
          "slug": "四、provide-inject"
        },
        {
          "level": 2,
          "title": "五、attrs",
          "slug": "五、attrs"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "导航守卫----不登录就不给看！",
      "frontmatter": {
        "title": "导航守卫----不登录就不给看！",
        "date": "2022-10-30T00:00:00.000Z",
        "tags": [
          "路由守卫"
        ],
        "categories": [
          "Vue Series"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Vue%20Series/define-router.html",
      "relativePath": "handbook/Vue Series/define-router.md",
      "key": "v-c30d43b6",
      "path": "/handbook/Vue%20Series/define-router.html",
      "headers": [
        {
          "level": 2,
          "title": "没有守卫时",
          "slug": "没有守卫时"
        },
        {
          "level": 2,
          "title": "一、全局路由守卫",
          "slug": "一、全局路由守卫"
        },
        {
          "level": 3,
          "title": "知识基础",
          "slug": "知识基础"
        },
        {
          "level": 3,
          "title": "路由守卫",
          "slug": "路由守卫"
        },
        {
          "level": 2,
          "title": "二、路由独享守卫",
          "slug": "二、路由独享守卫"
        },
        {
          "level": 3,
          "title": "知识基础",
          "slug": "知识基础-2"
        },
        {
          "level": 3,
          "title": "路由守卫",
          "slug": "路由守卫-2"
        },
        {
          "level": 2,
          "title": "三、组件内的守卫",
          "slug": "三、组件内的守卫"
        },
        {
          "level": 3,
          "title": "知识基础",
          "slug": "知识基础-3"
        },
        {
          "level": 3,
          "title": "路由守卫",
          "slug": "路由守卫-3"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "vue2和vue3的区别？先从响应式原理说起",
      "frontmatter": {
        "title": "vue2和vue3的区别？先从响应式原理说起",
        "date": "2022-10-29T00:00:00.000Z",
        "tags": [
          "vue2和vue3的区别"
        ],
        "categories": [
          "Vue Series"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Vue%20Series/diff-vue23.html",
      "relativePath": "handbook/Vue Series/diff-vue23.md",
      "key": "v-565a596b",
      "path": "/handbook/Vue%20Series/diff-vue23.html",
      "headers": [
        {
          "level": 2,
          "title": "一、什么是响应式？",
          "slug": "一、什么是响应式"
        },
        {
          "level": 2,
          "title": "二、vue2响应式原理？",
          "slug": "二、vue2响应式原理"
        },
        {
          "level": 3,
          "title": "1、响应式API",
          "slug": "_1、响应式api"
        },
        {
          "level": 3,
          "title": "2、响应式原理",
          "slug": "_2、响应式原理"
        },
        {
          "level": 3,
          "title": "3、缺点",
          "slug": "_3、缺点"
        },
        {
          "level": 2,
          "title": "三、vue3响应式原理？",
          "slug": "三、vue3响应式原理"
        },
        {
          "level": 3,
          "title": "1、响应式API",
          "slug": "_1、响应式api-2"
        },
        {
          "level": 3,
          "title": "2、响应式原理",
          "slug": "_2、响应式原理-2"
        },
        {
          "level": 3,
          "title": "3、对比vue2",
          "slug": "_3、对比vue2"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "在vue中，为什么不能用index作为key？",
      "frontmatter": {
        "title": "在vue中，为什么不能用index作为key？",
        "date": "2022-09-25T00:00:00.000Z",
        "tags": [
          "index"
        ],
        "categories": [
          "Vue Series"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Vue%20Series/key-index.html",
      "relativePath": "handbook/Vue Series/key-index.md",
      "key": "v-948b1d76",
      "path": "/handbook/Vue%20Series/key-index.html",
      "headers": [
        {
          "level": 2,
          "title": "一、key的作用是什么？",
          "slug": "一、key的作用是什么"
        },
        {
          "level": 2,
          "title": "二、什么是虚拟DOM？",
          "slug": "二、什么是虚拟dom"
        },
        {
          "level": 2,
          "title": "三、什么是diff算法?",
          "slug": "三、什么是diff算法"
        },
        {
          "level": 2,
          "title": "四、为什么不能用index作为key？",
          "slug": "四、为什么不能用index作为key"
        },
        {
          "level": 3,
          "title": "（1）index不能作为key--情景一",
          "slug": "_1-index不能作为key-情景一"
        },
        {
          "level": 3,
          "title": "（2）index不能作为key---情景二",
          "slug": "_2-index不能作为key-情景二"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "接得住三连问？XSS不再懵",
      "frontmatter": {
        "title": "接得住三连问？XSS不再懵",
        "date": "2022-12-11T00:00:00.000Z",
        "tags": "-XSS",
        "categories": [
          "浏览器"
        ]
      },
      "regularPath": "/handbook/%E6%B5%8F%E8%A7%88%E5%99%A8/XSS.html",
      "relativePath": "handbook/浏览器/XSS.md",
      "key": "v-54dc40c0",
      "path": "/handbook/%E6%B5%8F%E8%A7%88%E5%99%A8/XSS.html",
      "headers": [
        {
          "level": 2,
          "title": "highlight: a11y-dark\ntheme: cyanosis",
          "slug": "highlight-a11y-darktheme-cyanosis"
        },
        {
          "level": 2,
          "title": "一、什么是XSS？",
          "slug": "一、什么是xss"
        },
        {
          "level": 3,
          "title": "（1）XSS概念",
          "slug": "_1-xss概念"
        },
        {
          "level": 3,
          "title": "（2）存储型XSS",
          "slug": "_2-存储型xss"
        },
        {
          "level": 3,
          "title": "（3）反射型XSS",
          "slug": "_3-反射型xss"
        },
        {
          "level": 3,
          "title": "（4）基于DOM的XSS",
          "slug": "_4-基于dom的xss"
        },
        {
          "level": 2,
          "title": "二、XSS有哪些危害？",
          "slug": "二、xss有哪些危害"
        },
        {
          "level": 2,
          "title": "三、如何防范XSS？",
          "slug": "三、如何防范xss"
        },
        {
          "level": 3,
          "title": "（1）服务器对脚本进行过滤和转码",
          "slug": "_1-服务器对脚本进行过滤和转码"
        },
        {
          "level": 3,
          "title": "（2）充分利用CSP",
          "slug": "_2-充分利用csp"
        },
        {
          "level": 2,
          "title": "四、应用场景",
          "slug": "四、应用场景"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "路由带参，简简单单~",
      "frontmatter": {
        "title": "路由带参，简简单单~",
        "date": "2022-11-13T00:00:00.000Z",
        "tags": [
          "路由带参"
        ],
        "categories": [
          "Vue Series"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Vue%20Series/params.html",
      "relativePath": "handbook/Vue Series/params.md",
      "key": "v-4045a79d",
      "path": "/handbook/Vue%20Series/params.html",
      "headers": [
        {
          "level": 2,
          "title": "带参数的路由匹配",
          "slug": "带参数的路由匹配"
        },
        {
          "level": 3,
          "title": "一、query传递/接收路径参数",
          "slug": "一、query传递-接收路径参数"
        },
        {
          "level": 2,
          "title": "二、params传递/接收路径参数",
          "slug": "二、params传递-接收路径参数"
        },
        {
          "level": 3,
          "title": "1、router-link",
          "slug": "_1、router-link"
        },
        {
          "level": 3,
          "title": "2、router.push()",
          "slug": "_2、router-push"
        },
        {
          "level": 2,
          "title": "三、总结",
          "slug": "三、总结"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "快来学习javascript设计模式",
      "frontmatter": {
        "title": "快来学习javascript设计模式",
        "date": "2022-12-10T00:00:00.000Z",
        "tags": "-扁平化",
        "categories": [
          "Javascript"
        ]
      },
      "regularPath": "/handbook/%E6%89%8B%E5%86%99%E9%A2%98/flat.html",
      "relativePath": "handbook/手写题/flat.md",
      "key": "v-ffa9b532",
      "path": "/handbook/%E6%89%8B%E5%86%99%E9%A2%98/flat.html",
      "headers": [
        {
          "level": 2,
          "title": "highlight: a11y-dark\ntheme: channing-cyan",
          "slug": "highlight-a11y-darktheme-channing-cyan"
        },
        {
          "level": 2,
          "title": "一、数组的扁平化",
          "slug": "一、数组的扁平化"
        },
        {
          "level": 3,
          "title": "（1）Array.prototype.flat()",
          "slug": "_1-array-prototype-flat"
        },
        {
          "level": 3,
          "title": "（2）Array.prototype.toString()",
          "slug": "_2-array-prototype-tostring"
        },
        {
          "level": 3,
          "title": "（3）Array.prototype.concat()",
          "slug": "_3-array-prototype-concat"
        },
        {
          "level": 3,
          "title": "（4）使用Generator函数",
          "slug": "_4-使用generator函数"
        },
        {
          "level": 3,
          "title": "（5）Array.reduce()",
          "slug": "_5-array-reduce"
        },
        {
          "level": 2,
          "title": "二、对象的扁平化",
          "slug": "二、对象的扁平化"
        },
        {
          "level": 3,
          "title": "（1）手写对象扁平化",
          "slug": "_1-手写对象扁平化"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "码上【call，apply，bind】的手写",
      "frontmatter": {
        "title": "码上【call，apply，bind】的手写",
        "date": "2022-12-02T00:00:00.000Z",
        "tags": [
          "手写题"
        ],
        "categories": [
          "手写题"
        ]
      },
      "regularPath": "/handbook/%E6%89%8B%E5%86%99%E9%A2%98/call-apply-bind.html",
      "relativePath": "handbook/手写题/call-apply-bind.md",
      "key": "v-fd6d00aa",
      "path": "/handbook/%E6%89%8B%E5%86%99%E9%A2%98/call-apply-bind.html",
      "headers": [
        {
          "level": 2,
          "title": "highlight: a11y-dark\ntheme: healer-readable",
          "slug": "highlight-a11y-darktheme-healer-readable"
        },
        {
          "level": 2,
          "title": "一、call",
          "slug": "一、call"
        },
        {
          "level": 3,
          "title": "（1）官方用法",
          "slug": "_1-官方用法"
        },
        {
          "level": 3,
          "title": "（2）实现原理",
          "slug": "_2-实现原理"
        },
        {
          "level": 2,
          "title": "二、apply",
          "slug": "二、apply"
        },
        {
          "level": 3,
          "title": "（1）官方用法",
          "slug": "_1-官方用法-2"
        },
        {
          "level": 3,
          "title": "（2）实现原理",
          "slug": "_2-实现原理-2"
        },
        {
          "level": 2,
          "title": "三、bind",
          "slug": "三、bind"
        },
        {
          "level": 3,
          "title": "（1）官方用法",
          "slug": "_1-官方用法-3"
        },
        {
          "level": 3,
          "title": "（2）实现原理",
          "slug": "_2-实现原理-3"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "面试官：你如何实现大文件上传",
      "frontmatter": {
        "title": "面试官：你如何实现大文件上传",
        "date": "2022-12-15T00:00:00.000Z",
        "tags": "-大文件上传",
        "categories": [
          "面试题"
        ]
      },
      "regularPath": "/handbook/%E9%9D%A2%E8%AF%95%E9%A2%98/bigfileload.html",
      "relativePath": "handbook/面试题/bigfileload.md",
      "key": "v-cf20034c",
      "path": "/handbook/%E9%9D%A2%E8%AF%95%E9%A2%98/bigfileload.html",
      "headers": [
        {
          "level": 2,
          "title": "highlight: a11y-dark\ntheme: smartblue",
          "slug": "highlight-a11y-darktheme-smartblue"
        },
        {
          "level": 2,
          "title": "一、问题分析",
          "slug": "一、问题分析"
        },
        {
          "level": 2,
          "title": "一、解决方案",
          "slug": "一、解决方案"
        },
        {
          "level": 2,
          "title": "二、具体实现",
          "slug": "二、具体实现"
        },
        {
          "level": 3,
          "title": "1、前端",
          "slug": "_1、前端"
        },
        {
          "level": 2,
          "title": "（1）读取文件",
          "slug": "_1-读取文件"
        },
        {
          "level": 2,
          "title": "（2）创建切片",
          "slug": "_2-创建切片"
        },
        {
          "level": 2,
          "title": "（3）上传切片",
          "slug": "_3-上传切片"
        },
        {
          "level": 3,
          "title": "2、后端",
          "slug": "_2、后端"
        },
        {
          "level": 2,
          "title": "（1）接收切片",
          "slug": "_1-接收切片"
        },
        {
          "level": 2,
          "title": "（2）合并切片",
          "slug": "_2-合并切片"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "关于作者",
      "frontmatter": {
        "title": "关于作者",
        "date": "2022-10-15T14:20:00.000Z",
        "sidebar": "auto"
      },
      "regularPath": "/views/About/author.html",
      "relativePath": "views/About/author.md",
      "key": "v-0c9df344",
      "path": "/views/About/author.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "我的经历",
          "slug": "我的经历"
        },
        {
          "level": 2,
          "title": "目标",
          "slug": "目标"
        },
        {
          "level": 2,
          "title": "联系我",
          "slug": "联系我"
        },
        {
          "level": 2,
          "title": "联系我",
          "slug": "联系我-2"
        }
      ],
      "excerpt": "",
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "这是我的简历",
      "frontmatter": {
        "title": "这是我的简历",
        "date": "2022-12-15T14:20:00.000Z",
        "sidebar": "auto",
        "sticky": 1
      },
      "regularPath": "/views/Resume/resume.html",
      "relativePath": "views/Resume/resume.md",
      "key": "v-a6051270",
      "path": "/views/Resume/resume.html",
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "title": "快速上手",
      "frontmatter": {
        "title": "快速上手",
        "date": "2019-04-09T00:00:00.000Z"
      },
      "regularPath": "/views/other/guide.html",
      "relativePath": "views/other/guide.md",
      "key": "v-11de394e",
      "path": "/views/other/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "Use",
          "slug": "use"
        },
        {
          "level": 2,
          "title": "Play Together",
          "slug": "play-together"
        },
        {
          "level": 3,
          "title": "0.x",
          "slug": "_0-x"
        },
        {
          "level": 3,
          "title": "1.x",
          "slug": "_1-x"
        },
        {
          "level": 3,
          "title": "CLI",
          "slug": "cli"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ],
      "lastUpdated": "12/18/2022, 5:18:06 PM",
      "lastUpdatedTimestamp": 1671355086000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "青训营笔记 Tags"
      },
      "regularPath": "/tag/%E9%9D%92%E8%AE%AD%E8%90%A5%E7%AC%94%E8%AE%B0/",
      "key": "v-27c59f82",
      "path": "/tag/青训营笔记/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Promise Tags"
      },
      "regularPath": "/tag/Promise/",
      "key": "v-d0674184",
      "path": "/tag/Promise/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "for-of-in Tags"
      },
      "regularPath": "/tag/for-of-in/",
      "key": "v-1f35fe62",
      "path": "/tag/for-of-in/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "async-await Tags"
      },
      "regularPath": "/tag/async-await/",
      "key": "v-5dd7c1b4",
      "path": "/tag/async-await/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Git Tags"
      },
      "regularPath": "/tag/Git/",
      "key": "v-32555732",
      "path": "/tag/Git/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Generator Tags"
      },
      "regularPath": "/tag/Generator/",
      "key": "v-9114abf4",
      "path": "/tag/Generator/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "javascript Tags"
      },
      "regularPath": "/tag/javascript/",
      "key": "v-07a3e910",
      "path": "/tag/javascript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "数组 Tags"
      },
      "regularPath": "/tag/%E6%95%B0%E7%BB%84/",
      "key": "v-197ac33a",
      "path": "/tag/数组/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "闭包 Tags"
      },
      "regularPath": "/tag/%E9%97%AD%E5%8C%85/",
      "key": "v-eec8ec48",
      "path": "/tag/闭包/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "深浅拷贝 Tags"
      },
      "regularPath": "/tag/%E6%B7%B1%E6%B5%85%E6%8B%B7%E8%B4%9D/",
      "key": "v-d74bd976",
      "path": "/tag/深浅拷贝/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "设计模式 Tags"
      },
      "regularPath": "/tag/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/",
      "key": "v-ae3001b6",
      "path": "/tag/设计模式/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "浏览器的事件循环 Tags"
      },
      "regularPath": "/tag/%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%BE%AA%E7%8E%AF/",
      "key": "v-1960ed2f",
      "path": "/tag/浏览器的事件循环/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "跨域 Tags"
      },
      "regularPath": "/tag/%E8%B7%A8%E5%9F%9F/",
      "key": "v-67cf2c0a",
      "path": "/tag/跨域/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "new原理 Tags"
      },
      "regularPath": "/tag/new%E5%8E%9F%E7%90%86/",
      "key": "v-970225a0",
      "path": "/tag/new原理/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "作用域和作用域链 Tags"
      },
      "regularPath": "/tag/%E4%BD%9C%E7%94%A8%E5%9F%9F%E5%92%8C%E4%BD%9C%E7%94%A8%E5%9F%9F%E9%93%BE/",
      "key": "v-033f6638",
      "path": "/tag/作用域和作用域链/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "类型转换 Tags"
      },
      "regularPath": "/tag/%E7%B1%BB%E5%9E%8B%E8%BD%AC%E6%8D%A2/",
      "key": "v-0b8093b7",
      "path": "/tag/类型转换/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "关键字this Tags"
      },
      "regularPath": "/tag/%E5%85%B3%E9%94%AE%E5%AD%97this/",
      "key": "v-28ccba78",
      "path": "/tag/关键字this/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "原型和原型链 Tags"
      },
      "regularPath": "/tag/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE/",
      "key": "v-53c426ac",
      "path": "/tag/原型和原型链/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "前端路由 Tags"
      },
      "regularPath": "/tag/%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1/",
      "key": "v-b612eeb2",
      "path": "/tag/前端路由/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "url Tags"
      },
      "regularPath": "/tag/url/",
      "key": "v-322b436c",
      "path": "/tag/url/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "浏览器 Tags"
      },
      "regularPath": "/tag/%E6%B5%8F%E8%A7%88%E5%99%A8/",
      "key": "v-0c5c4c5e",
      "path": "/tag/浏览器/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "洋葱模型 Tags"
      },
      "regularPath": "/tag/%E6%B4%8B%E8%91%B1%E6%A8%A1%E5%9E%8B/",
      "key": "v-1c98b280",
      "path": "/tag/洋葱模型/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "HTTP Tags"
      },
      "regularPath": "/tag/HTTP/",
      "key": "v-184d5f86",
      "path": "/tag/HTTP/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "类型 Tags"
      },
      "regularPath": "/tag/%E7%B1%BB%E5%9E%8B/",
      "key": "v-b6f5cd0c",
      "path": "/tag/类型/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "类型推论和类型断言 Tags"
      },
      "regularPath": "/tag/%E7%B1%BB%E5%9E%8B%E6%8E%A8%E8%AE%BA%E5%92%8C%E7%B1%BB%E5%9E%8B%E6%96%AD%E8%A8%80/",
      "key": "v-5a4cdae8",
      "path": "/tag/类型推论和类型断言/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "组件通信 Tags"
      },
      "regularPath": "/tag/%E7%BB%84%E4%BB%B6%E9%80%9A%E4%BF%A1/",
      "key": "v-6e72c1b9",
      "path": "/tag/组件通信/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "路由守卫 Tags"
      },
      "regularPath": "/tag/%E8%B7%AF%E7%94%B1%E5%AE%88%E5%8D%AB/",
      "key": "v-047eaeee",
      "path": "/tag/路由守卫/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vue2和vue3的区别 Tags"
      },
      "regularPath": "/tag/vue2%E5%92%8Cvue3%E7%9A%84%E5%8C%BA%E5%88%AB/",
      "key": "v-712b18d6",
      "path": "/tag/vue2和vue3的区别/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "index Tags"
      },
      "regularPath": "/tag/index/",
      "key": "v-7dd2b672",
      "path": "/tag/index/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "-XSS Tags"
      },
      "regularPath": "/tag/-XSS/",
      "key": "v-1b42b88c",
      "path": "/tag/-XSS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "路由带参 Tags"
      },
      "regularPath": "/tag/%E8%B7%AF%E7%94%B1%E5%B8%A6%E5%8F%82/",
      "key": "v-0a2b6856",
      "path": "/tag/路由带参/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "-扁平化 Tags"
      },
      "regularPath": "/tag/-%E6%89%81%E5%B9%B3%E5%8C%96/",
      "key": "v-1bc5c70c",
      "path": "/tag/-扁平化/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "手写题 Tags"
      },
      "regularPath": "/tag/%E6%89%8B%E5%86%99%E9%A2%98/",
      "key": "v-0b58b14a",
      "path": "/tag/手写题/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "-大文件上传 Tags"
      },
      "regularPath": "/tag/-%E5%A4%A7%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0/",
      "key": "v-9b8daaa2",
      "path": "/tag/-大文件上传/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "字节青训营笔记 Categories"
      },
      "regularPath": "/categories/%E5%AD%97%E8%8A%82%E9%9D%92%E8%AE%AD%E8%90%A5%E7%AC%94%E8%AE%B0/",
      "key": "v-599a76af",
      "path": "/categories/字节青训营笔记/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "ES6 Categories"
      },
      "regularPath": "/categories/ES6/",
      "key": "v-7eff4a05",
      "path": "/categories/ES6/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Git Categories"
      },
      "regularPath": "/categories/Git/",
      "key": "v-7f008cdb",
      "path": "/categories/Git/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Javascript Categories"
      },
      "regularPath": "/categories/Javascript/",
      "key": "v-b6345f38",
      "path": "/categories/Javascript/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "NodeJS Categories"
      },
      "regularPath": "/categories/NodeJS/",
      "key": "v-466f3074",
      "path": "/categories/NodeJS/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Typescript Categories"
      },
      "regularPath": "/categories/Typescript/",
      "key": "v-fabcff68",
      "path": "/categories/Typescript/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Vue Series Categories"
      },
      "regularPath": "/categories/Vue%20Series/",
      "key": "v-3f0d1106",
      "path": "/categories/Vue Series/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "浏览器 Categories"
      },
      "regularPath": "/categories/%E6%B5%8F%E8%A7%88%E5%99%A8/",
      "key": "v-0a4268d2",
      "path": "/categories/浏览器/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "手写题 Categories"
      },
      "regularPath": "/categories/%E6%89%8B%E5%86%99%E9%A2%98/",
      "key": "v-093ecdbe",
      "path": "/categories/手写题/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "面试题 Categories"
      },
      "regularPath": "/categories/%E9%9D%A2%E8%AF%95%E9%A2%98/",
      "key": "v-172f4c96",
      "path": "/categories/面试题/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - Javascript | Categories"
      },
      "regularPath": "/categories/Javascript/page/2/",
      "key": "v-57ffccd9",
      "path": "/categories/Javascript/page/2/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "简历",
        "icon": "reco-message",
        "items": [
          {
            "text": "我的简历",
            "link": "/views/Resume/resume"
          }
        ]
      },
      {
        "text": "关于",
        "icon": "reco-message",
        "items": [
          {
            "text": "Gitee",
            "link": "https://gitee.com/fieemiracle",
            "icon": "reco-mayun"
          },
          {
            "text": "Leetcode",
            "link": "https://leetcode.cn/u/fieemiracle/",
            "icon": "reco-coding"
          },
          {
            "text": "稀土掘金",
            "link": "https://juejin.cn/user/3316551988553709/posts",
            "icon": "reco-juejin"
          },
          {
            "text": "Github",
            "link": "https://github.com/fieemiracle",
            "icon": "reco-github"
          },
          {
            "text": "CSDN",
            "link": "https://mp.csdn.net/mp_blog/manage/article?spm=1010.2135.3001.5448",
            "icon": "reco-csdn"
          }
        ]
      }
    ],
    "subSidebar": "auto",
    "sidebar": "auto",
    "type": "blog",
    "smooth": "true",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "目录"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "1156743527@qq.com",
        "link": "https://www.recoluan.com"
      },
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "valineConfig": {
      "appId": "OcpE2k26zVB0L3vtcpYl0uPK-gzGzoHsz",
      "appKey": "rp6d1uq9qMATS2zJnuviZ3ZS",
      "showComment": false,
      "placeholder": "发表评论~",
      "visitor": true,
      "avatarForce": true,
      "avatar": "monsterid"
    },
    "locales": {
      "/": {
        "recoLocales": {
          "homeBlog": {
            "lang": "zh-CN",
            "article": "美文",
            "tag": "标识",
            "category": "类别",
            "friendLink": "友链"
          },
          "pagation": {
            "prev": "上一页",
            "next": "下一页",
            "go": "前往",
            "jump": "跳转至"
          }
        }
      },
      "/en/": {
        "recoLocales": {
          "homeBlog": {
            "lang": "en-US",
            "article": "articles",
            "tag": "tags",
            "category": "categories",
            "friendLink": "friendLink"
          },
          "pagation": {
            "prev": "previous page",
            "next": "next page",
            "go": "travel to",
            "jump": "jump to"
          }
        }
      }
    },
    "displayAllHeaders": true,
    "search": true,
    "lastUpdated": "Last Updated",
    "author": "fieemiracle",
    "authorAvatar": "/avatar.jpg",
    "record": "xxxx",
    "startYear": "2022"
  }
}