/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "青训营笔记": {
      "key": "青训营笔记",
      "scope": "tags",
      "path": "/tag/青训营笔记/",
      "pageKeys": [
        "v-4e2589a8",
        "v-3caecaa8"
      ]
    },
    "Promise": {
      "key": "Promise",
      "scope": "tags",
      "path": "/tag/Promise/",
      "pageKeys": [
        "v-fa9d4098",
        "v-34526722"
      ]
    },
    "for-of-in": {
      "key": "for-of-in",
      "scope": "tags",
      "path": "/tag/for-of-in/",
      "pageKeys": [
        "v-04c3f5f4"
      ]
    },
    "async-await": {
      "key": "async-await",
      "scope": "tags",
      "path": "/tag/async-await/",
      "pageKeys": [
        "v-29052a20"
      ]
    },
    "Git": {
      "key": "Git",
      "scope": "tags",
      "path": "/tag/Git/",
      "pageKeys": [
        "v-2f587472"
      ]
    },
    "Generator": {
      "key": "Generator",
      "scope": "tags",
      "path": "/tag/Generator/",
      "pageKeys": [
        "v-7396af44"
      ]
    },
    "javascript": {
      "key": "javascript",
      "scope": "tags",
      "path": "/tag/javascript/",
      "pageKeys": [
        "v-740c6c70"
      ]
    },
    "数组": {
      "key": "数组",
      "scope": "tags",
      "path": "/tag/数组/",
      "pageKeys": [
        "v-89b357f0"
      ]
    },
    "闭包": {
      "key": "闭包",
      "scope": "tags",
      "path": "/tag/闭包/",
      "pageKeys": [
        "v-1e72e1f0"
      ]
    },
    "深浅拷贝": {
      "key": "深浅拷贝",
      "scope": "tags",
      "path": "/tag/深浅拷贝/",
      "pageKeys": [
        "v-415673b4"
      ]
    },
    "设计模式": {
      "key": "设计模式",
      "scope": "tags",
      "path": "/tag/设计模式/",
      "pageKeys": [
        "v-3cfeb528"
      ]
    },
    "浏览器的事件循环": {
      "key": "浏览器的事件循环",
      "scope": "tags",
      "path": "/tag/浏览器的事件循环/",
      "pageKeys": [
        "v-46361b30"
      ]
    },
    "跨域": {
      "key": "跨域",
      "scope": "tags",
      "path": "/tag/跨域/",
      "pageKeys": [
        "v-448482b0"
      ]
    },
    "new原理": {
      "key": "new原理",
      "scope": "tags",
      "path": "/tag/new原理/",
      "pageKeys": [
        "v-5a59ae30"
      ]
    },
    "作用域和作用域链": {
      "key": "作用域和作用域链",
      "scope": "tags",
      "path": "/tag/作用域和作用域链/",
      "pageKeys": [
        "v-c94833b0"
      ]
    },
    "类型转换": {
      "key": "类型转换",
      "scope": "tags",
      "path": "/tag/类型转换/",
      "pageKeys": [
        "v-18ae93ea"
      ]
    },
    "关键字this": {
      "key": "关键字this",
      "scope": "tags",
      "path": "/tag/关键字this/",
      "pageKeys": [
        "v-b020dfbc"
      ]
    },
    "原型和原型链": {
      "key": "原型和原型链",
      "scope": "tags",
      "path": "/tag/原型和原型链/",
      "pageKeys": [
        "v-64b915e8"
      ]
    },
    "前端路由": {
      "key": "前端路由",
      "scope": "tags",
      "path": "/tag/前端路由/",
      "pageKeys": [
        "v-2534b6da"
      ]
    },
    "url": {
      "key": "url",
      "scope": "tags",
      "path": "/tag/url/",
      "pageKeys": [
        "v-66562fc2",
        "v-a7e376b4"
      ]
    },
    "浏览器": {
      "key": "浏览器",
      "scope": "tags",
      "path": "/tag/浏览器/",
      "pageKeys": [
        "v-66562fc2",
        "v-a7e376b4"
      ]
    },
    "洋葱模型": {
      "key": "洋葱模型",
      "scope": "tags",
      "path": "/tag/洋葱模型/",
      "pageKeys": [
        "v-1230f3c8"
      ]
    },
    "HTTP": {
      "key": "HTTP",
      "scope": "tags",
      "path": "/tag/HTTP/",
      "pageKeys": [
        "v-81c9c4ec"
      ]
    },
    "类型": {
      "key": "类型",
      "scope": "tags",
      "path": "/tag/类型/",
      "pageKeys": [
        "v-71ef9468"
      ]
    },
    "类型推论和类型断言": {
      "key": "类型推论和类型断言",
      "scope": "tags",
      "path": "/tag/类型推论和类型断言/",
      "pageKeys": [
        "v-4d47a048"
      ]
    },
    "组件通信": {
      "key": "组件通信",
      "scope": "tags",
      "path": "/tag/组件通信/",
      "pageKeys": [
        "v-bf6ce736"
      ]
    },
    "路由守卫": {
      "key": "路由守卫",
      "scope": "tags",
      "path": "/tag/路由守卫/",
      "pageKeys": [
        "v-c30d43b6"
      ]
    },
    "vue2和vue3的区别": {
      "key": "vue2和vue3的区别",
      "scope": "tags",
      "path": "/tag/vue2和vue3的区别/",
      "pageKeys": [
        "v-565a596b"
      ]
    },
    "index": {
      "key": "index",
      "scope": "tags",
      "path": "/tag/index/",
      "pageKeys": [
        "v-948b1d76"
      ]
    },
    "-XSS": {
      "key": "-XSS",
      "scope": "tags",
      "path": "/tag/-XSS/",
      "pageKeys": [
        "v-54dc40c0"
      ]
    },
    "路由带参": {
      "key": "路由带参",
      "scope": "tags",
      "path": "/tag/路由带参/",
      "pageKeys": [
        "v-4045a79d"
      ]
    },
    "-扁平化": {
      "key": "-扁平化",
      "scope": "tags",
      "path": "/tag/-扁平化/",
      "pageKeys": [
        "v-ffa9b532"
      ]
    },
    "手写题": {
      "key": "手写题",
      "scope": "tags",
      "path": "/tag/手写题/",
      "pageKeys": [
        "v-fd6d00aa"
      ]
    },
    "-大文件上传": {
      "key": "-大文件上传",
      "scope": "tags",
      "path": "/tag/-大文件上传/",
      "pageKeys": [
        "v-cf20034c"
      ]
    }
  },
  "categories": {
    "字节青训营笔记": {
      "key": "字节青训营笔记",
      "scope": "categories",
      "path": "/categories/字节青训营笔记/",
      "pageKeys": [
        "v-4e2589a8",
        "v-3caecaa8"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "categories",
      "path": "/categories/ES6/",
      "pageKeys": [
        "v-fa9d4098",
        "v-04c3f5f4",
        "v-29052a20",
        "v-34526722",
        "v-7396af44"
      ]
    },
    "Git": {
      "key": "Git",
      "scope": "categories",
      "path": "/categories/Git/",
      "pageKeys": [
        "v-2f587472"
      ]
    },
    "Javascript": {
      "key": "Javascript",
      "scope": "categories",
      "path": "/categories/Javascript/",
      "pageKeys": [
        "v-740c6c70",
        "v-89b357f0",
        "v-1e72e1f0",
        "v-415673b4",
        "v-3cfeb528",
        "v-46361b30",
        "v-448482b0",
        "v-5a59ae30",
        "v-c94833b0",
        "v-18ae93ea",
        "v-b020dfbc",
        "v-64b915e8",
        "v-2534b6da",
        "v-66562fc2",
        "v-a7e376b4",
        "v-ffa9b532"
      ]
    },
    "NodeJS": {
      "key": "NodeJS",
      "scope": "categories",
      "path": "/categories/NodeJS/",
      "pageKeys": [
        "v-1230f3c8",
        "v-81c9c4ec"
      ]
    },
    "Typescript": {
      "key": "Typescript",
      "scope": "categories",
      "path": "/categories/Typescript/",
      "pageKeys": [
        "v-71ef9468",
        "v-4d47a048"
      ]
    },
    "Vue Series": {
      "key": "Vue Series",
      "scope": "categories",
      "path": "/categories/Vue Series/",
      "pageKeys": [
        "v-bf6ce736",
        "v-c30d43b6",
        "v-565a596b",
        "v-948b1d76",
        "v-4045a79d"
      ]
    },
    "浏览器": {
      "key": "浏览器",
      "scope": "categories",
      "path": "/categories/浏览器/",
      "pageKeys": [
        "v-54dc40c0"
      ]
    },
    "手写题": {
      "key": "手写题",
      "scope": "categories",
      "path": "/categories/手写题/",
      "pageKeys": [
        "v-fd6d00aa"
      ]
    },
    "面试题": {
      "key": "面试题",
      "scope": "categories",
      "path": "/categories/面试题/",
      "pageKeys": [
        "v-cf20034c"
      ]
    }
  },
  "timeline": {}
}